[build-system]
requires = ["setuptools==80.9.0"]
build-backend = "setuptools.build_meta"

[project]
name = "docassemble.InterviewStats"
version = "0.6.0"
description = "A docassemble interview to view statistics from other saved interview responses."
readme = "README.md"
authors = [
    { name="Suffolk Legal Innovation and Technology Lab", email="litlab@suffolk.edu" },
]
dependencies = [
    "numpy>=1.0.4",
    "pandas>=1.4.2",
    "requests>=2.27.1",
]
license = "MIT"
license-files = ["LICENSE*"]

[project.urls]
GitHub = "https://github.com/SuffolkLITLab/docassemble-InterviewStats"

[tool.setuptools.packages.find]
where = ["."]

[dependency-groups]
dev = [
    "docassemble.base >= 1.9.0",
    "docassemble.webapp >= 1.9.0",
    "mypy",
    "types-requests",
    "pandas-stubs",
    "pytest"
]

# per-module options:
[[tool.mypy.overrides]]
module= "docassemble.webapp.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "docassemble.base.*"
ignore_missing_imports = true

